### ISSUE TITLE
error occurs while running the playbook

### ISSUE THREAD

**Issue by huiminzeng** [marji/ansible-docker-compose-example#1]
Hello, thanks for the sharing.  I ran the playbook, but then the error occured: Failed to import docker-py - No module named docker. Try `pip install docker-py`.

However, once i installed docker-py. New issue occured: can not have both the docker-py and docker python modules installed together.

Then i uninstalled one of them, but the first error came again: Failed to import docker-py - No module named docker. Try `pip install docker-py`.

So, could you please tell me how to solve it? Thank you very much. I have read a lot of instances on Github, but the solutions to the similar error never works for me......

Thank you!

**Comment by tkrishtop** [comment]
Hello @huiminzeng,

you didn't provide any info about your OS, docker-compose and ansible versions.
The wild guess: maybe you use MacOS. Docker and ansible work great with Ubuntu but not with macOS.

The solution which could work for you is to use vagrant ubuntu/bento17  https://app.vagrantup.com/bento/boxes/ubuntu-17.04 and install docker-compose, ansible etc from scratch on this friendly Ubuntu. This will allow you to have a stable and true isolated Linux environment.

**Comment by huiminzeng** [comment]
Thank you! @tkrishtop . I just forget them. By the way, i did't doing the example. I was trying to deploy other applications.

OS: Ubuntu 16.04.4 LTS

docker-compose: 1.17.1, build 6d101fb

ansible version:
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
 configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

Thank you!

**Comment by tkrishtop** [comment]
Hello @huiminzeng ,
you're are using quite old versions of everything, do you consider an upgrade?
Could you please provide here an output of `pip list | grep docker` ?
If docker-py is really installed, maybe try to specify a path to it in ansible playbook:
`- hosts: <host>`
  `environment:`
`    PYTHONPATH: "/home/path/.local/lib/python2.7/site-packages"`

**Comment by huiminzeng** [comment]
hi! @tkrishtop it is really kind of you! 
<img width="235" alt="docker info" src="https://user-images.githubusercontent.com/38716719/39628798-745d5996-4faa-11e8-9070-4d1636ed233a.PNG">

Moreover, i tried the path specification. But it still is the same error.

thx

**Comment by tkrishtop** [comment]
Hi @huiminzeng,

- really, could you consider to upgrade your Ubuntu version? I have Vagrantfile (ubuntu/bento 17.10) with provision script to install ansible/docker-compose which works just fine and could send it to you. 

- try to reinstall docker-py, maybe the issue is in dependencies of docker-py
`pip uninstall docker-py`
`pip install docker-py --ignore-installed`

**Comment by huiminzeng** [comment]
Wow! @tkrishtop  Thank you very much!  But i just can not use ubuntu 17.10. I am trying to deploy rocketchat with ansible. But i tried ubuntu 17.10, where Rocketchat doesn't work so fine.  But thanks!

i will try your second tip. THX!

**Comment by tkrishtop** [comment]
@huiminzeng , I made it work in vagrant for ubuntu 16.04. Here it is (don't forget to delete `.vagrant` before `vagrant up`)

Vagrantfile

`Vagrant.configure("2") do |config|`
`  config.vm.provider "virtualbox" do |vb, override|`
`    vb.memory = 4096`
`    vb.cpus = 2`
`    override.vm.box = "bento/ubuntu-16.04"`
`  end`
`  config.vm.provision :shell, :path => "provision.sh"`
`end`

provision.sh

`#!/bin/bash`
`sudo apt-get update`
`groupadd --gid 993 docker`
`usermod -aG docker vagrant`
`sudo apt-get install docker -y`
`sudo apt-get install docker-compose -y`
`sudo apt-get install -y ansible`
`sudo apt-get install -y python-pip`
`pip install docker-py`

Now you could execute your ansible playbook without any errors.

**Comment by huiminzeng** [comment]
Hi! @tkrishtop I just got your solution, and I will try it! Thanks a lot! it is really kind of you to help me so much!

**Comment by huiminzeng** [comment]
Hello @tkrishtop, your solution works for me! the error doesn't occur any more. But there is another one... 
<img width="410" alt="new problem" src="https://user-images.githubusercontent.com/38716719/39692296-bd2f4bba-51e0-11e8-9354-4db51408f42a.PNG">
And this is my playbook.
<img width="157" alt="playbook" src="https://user-images.githubusercontent.com/38716719/39692308-c95cbe9a-51e0-11e8-8106-92b50961ab25.PNG">
I think it is still related to the docker_service, because task1 (connection test) just works fine after I add # to all the lines of the second tast (rocketchat installation)
I will appreciate it if you could please have a look! Thx!
